# Generated by Django 3.0.3 on 2020-03-07 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('priority_planners', '0002_remove_update_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='title',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
